### ISSUE TITLE
로그인 기능 추가 문제

### ISSUE THREAD

**Issue by daeng325** [kookmin-sw/2019-cap1-2019_10#1]
사용자 로그인 기능을 추가하여 추천 알고리즘을 구현할 것인지에 대해 공유하기

**Comment by ddi04078** [comment]
사용자 기반의 추천 알고리즘을 작성할 경우, 데이터 확보가 필요. 현재는 데이터가 없으므로 일단 랜덤 추출로 방향을 잡고 후에 발전시키는 게 좋을듯 함.

**Comment by daeng325** [comment]
사용자 로그인 기능을 추가한다면, 그에 해당하는 기능은 사용자가 지금까지 추천받은 노래 리스트를 볼 수 있는 기능이 될 것이다.

**Comment by daeng325** [comment]
로그인 기능 추가하기로 함. user table의 entry는 id, 닉네임, 비밀번호 가 될 것이다. 
앞서 말했듯이, 기능은 사용자가 지금까지 추천받은 노래 리스트를 볼 수 있게 하는 기능을 구현할 것임.
