### ISSUE TITLE
최종 감정 결과 도출방법 계획

### ISSUE THREAD

**Issue by ddi04078** [kookmin-sw/2019-cap1-2019_10#10]
#10 표정과 음성 등 여러 source로부터 나온 감정 결과를 어떻게 종합할 것인지에 대한 구체적인 계획 필요

**Comment by ddi04078** [comment]
표정과 음성 분석 결과가 어떻게 나올지는 구현후에 알 수 있으므로, 비율을 달리해 종합해보면서 여러 테스트를 거친후 최종 감정 결과를 도출하기로 한다.

**Comment by ddi04078** [comment]
구현 중에 알게되는 결과도출방법을 comment로 추가하자

**Comment by ddi04078** [comment]
예를들어, 표정이 주 감정이 행복이고 음성의 주 감정이 슬픔일 때 등, 연관이 거의 없는 경우에 최종 결과를 어떻게 도출할 것인지에 대해도 논의가 필요

**Comment by ddi04078** [comment]
위의 Comment에 대한 논의 결과 : 어플의 튜토리얼에서 감정에 진솔하게 대답하라고 설명을 할거고, 우리 취지도 '사용자가 감정을 속였는지 맞혀보겠다'가 아니다. 만약 그럼에도 불구하고 그렇게 했다면, 표정을 통한 감성분석과 음성을 통한 감성분석의 반영비율에 따라 결과를 내는 방향으로 진행하기로 한다. 반영비율은 테스트를 통해 확정지을 것 같다.

**Comment by daeng325** [comment]
MS api 에서는 결과가 8가지가 나오는데 speech-emotion-model은 결과가 string 하나만 나온다.  그것을 어떻게 종합할 것인지 논의해봐야 한다.
