### ISSUE TITLE
DB 테이블 설계 문제 

### ISSUE THREAD

**Issue by wsubin** [kookmin-sw/2019-cap1-2019_10#13]
알고리즘 설계를 반영하여 기존의 테이블 설계를 알고리즘에 맞게 바꿀 것.

**Comment by wsubin** [comment]
기존의 테이블은  music list 테이블 에 노래를 모두 담아 놨는데, 알고리즘 설계에 맞게하려면 테이블을 emotion에 따라 노래를 분류해야 하는 편이 좋을 것 같다.

**Comment by daeng325** [comment]
테이블 설계가 어떻게 됐는지 기록해주길 바람
