### ISSUE TITLE
앱 갤러리 기능

### ISSUE THREAD

**Issue by daeng325** [kookmin-sw/2019-cap1-2019_10#15]
본래 계획에 따르면, 앱을 실행한 후 모델이 나오고 
카메라를 사용해 바로 사진을 찍을 것인지 , 아니면 갤러리에 있는 사진을 이용할 것인지 사용자가 선택할 수 있게 할 예정이었다. 

그런데, 교수님의 피드백을 받은 후 사용자가 알 수 없게 얼굴표정에서 감정을 분석할 수 있게끔 할 방법을 생각해보니, 갤러리를 사용하는 방안이 모호해질 것 같다. 

이에 대한 방안을 생각해보자.

**Comment by daeng325** [comment]
갤러리를 활용할 수 있다고 가정해보자.

만약 갤러리를 통해 친구의 표정으로 감정을 분석해보고 싶다고 한다면, "오늘 기분은 어떠니?" 라고 물어보는 기능 자체가 불필요할 것이다. 

그렇다면 음성 인식으로 감정을 분석하는 방법은 사용자가 할지 말지 결정할 수 있게끔 해야 할까?

**Comment by ddi04078** [comment]
(뱡향전환 후)
![image](https://user-images.githubusercontent.com/18157668/55788944-4d7bf480-5af4-11e9-9d51-03d55d1e6a26.png)
얼굴인식을 중점적으로 시스템을 개발할 것이므로 갤러리 기능을 넣을 수 있음. 
로그인한 사용자에게 갤러리기능을 제공. 메뉴 버튼을 누르면 '추천받은 노래 목록'과 '갤러리에서 선택'을 할 수 있게 함.

**Comment by Jeunna** [comment]
너무 부가적인 기능이라 갤러리 기능은 빼기로 함
