### ISSUE TITLE
어플 Camera 관련 issues

### ISSUE THREAD

**Issue by Jeunna** [kookmin-sw/2019-cap1-2019_10#16]
- [x] camera permission 때문에 한 번에 카메라가 안뜸. 한 번 껐다키면 적용이 되어있음
그래서 permission을 먼저 체크하기 위해 sleep(1000)을 넣어놨는데 수정이 필요함

- [x] 사진을 저장할건지 사진을 캡쳐하고 저장하기 위해서는 경로를 찾아서 저장을 해줘야하는데 현재 아이폰, 안드로이드 그리고 그 외를 생각해서 코드를 짜놓긴 했는데 파일 경로를 다시 생각해서 수정을 해야하고 사진 자체를 어떻게 할 건지 정해야함.

- [x] 카메라를 안띄우고 얼굴 인식을 하기 위해선 얼굴 자체가 일단 카메라 상에 들어와있어야 하기 때문에 이를 어떻게 할건지. 예를 들어 벗어나면 캐릭터가 얼굴이 제대로 안보인다고 말을 해준다던가

**Comment by eunchae0280** [comment]
피드백에 의하면 사용자가 인식이 되는 것을 모르게하는 게 우선인데, 처음에 말하고 시작하지않으면 카메라를 벗어나는 일이 매번 발생할 것 같음. 그래서 얼굴을 인식하기전 화면을 제대로 봐달라고 한 다음 랜덤으로 대화로 진행되면서 랜덤으로 캡처하는 방법이 낫지 않을까..?

**Comment by daeng325** [comment]
두 번째에 사진 자체를 어떻게 할 건지 정해야 한다는 게 무슨 뜻인지 설명해주길 바람.

**Comment by Jeunna** [comment]
사진을
1. 사진을 핸드폰에 저장을 한 후에 전송을 하는 방향
2. 저장하지 않고 전송하는 방향

을 정하고

처음에 제대로 봐달라고 해도 이게 자기 자신의 얼굴이 보이지 않으면 중간중간 벗어날 경우가 많으니까 
 많이 벗어나서 인식이 안될 경우에는 
1. 화면 상에 이펙트를 띄운다든지 
2. 캐릭터가 얼굴이 제대로 안보인다고 말을 해준다든지 

하는 방향으로 얼굴이 화면상에서 아예 빠져나가지 않도록 조절을 해줘야할 거 같은데

**Comment by daeng325** [comment]
사진은 2번 방향으로 가는 게 나을 것 같고,

처음에 얼굴을 인식해야 할 때는 아무 말 없이 인식하고, 얼굴이 인식안되면 그때 이펙트 띄운다거나 해야 되지 않을까? 
아예 처음부터 화면 똑바로 봐주세요 라고 말하면 사용자가 모르게 하는 게 아닐 것 같음.
