### ISSUE TITLE
감정 테이블 분류 문제

### ISSUE THREAD

**Issue by wsubin** [kookmin-sw/2019-cap1-2019_10#17]
현재는 API에서 주어진 감정을 기준으로 happiness, surprise, sadness, fear, anger_contempt_disgust, neutral 로 나누었는데, 단지 API의 감정 값을 쓰는 것이 아닌  감정 분류에 대한 기준이 필요할 것 같다.

**Comment by wsubin** [comment]
미국이 심리학자들이 분류한 인간의 6가지 감정은 happiness, sadness, anger, fear, disgust, surprise 인데 이렇게 6개의 감정을 분류하는 것이 더 나을 것 같음.

**Comment by ddi04078** [comment]
8개의 감정 -> 6개의 감정(중립을 빼고, anger_contempt_disgust에서 anger과 contempt_disgust로 나눔)
