### ISSUE TITLE
음성-감정모델 피드백과 논의

### ISSUE THREAD

**Issue by eunchae0280** [kookmin-sw/2019-cap1-2019_10#18]
감정결과를 도출하기위해서 다양한 요소들이 결합될 수 있다. 얼굴표정을 인식한 이미지, 목소리, Bio리듬 등이 반영될 수 있다. 최종 한 결과를 도출하기 위해서 weight값을 다르게 주어 반영할 수 있다. 
일단 인식률이 높은 이미지 인식 api의 결과에 의존하기로 한다.

**Comment by eunchae0280** [comment]
첫번째, 음성-감정모델의 정확률을 고려하여 반영비율을 낮게라도 반영했을때,
얼굴인식에 대한 정확률을 높일수도, 무디게 할 수 있다. 이런 상황을 어떻게 할 것인가?

두번째, 얼굴인식의 결과로 모호한 결과가 나왔을때, 음성-감정모델의 결과가 도움이 될 수 있지 않을까?

**Comment by ddi04078** [comment]
전체적인 방향을 변경하기로 함 !!
음성인식은 얼굴인식과 별개로 진행할 수 있고, 정확률을 높이는 방법으로 사용할 것임
![image](https://user-images.githubusercontent.com/18157668/55788625-9c755a00-5af3-11e9-979f-0d3475183f5c.png)

**Comment by eunchae0280** [comment]
음성-감정모델의 정확률을 높일 방법이 생겼다. 
https://github.com/MITESHPUTHRANNEU/Speech-Emotion-Analyzer
성별이 구분되고 5가지의 감정에대해서 70%의 정확률을 가지는 학습된모델을 사용해보자. 
70%이면 이미지 인식결과와 적절한 앙상블을 통해 최종결과에 반영할 수 있을것 같다.

**Comment by eunchae0280** [comment]
하지만 외국음성을 가지고 학습된 모델이라 외국어로 입력을 넣어야 정확률이 높지않을까?
한국어 음성을 넣었을 때 정확도가 얼마나 나오는지 측정해 봐야한다.
일단 모델을 돌려보는 것을 목표로 두자.
