### ISSUE TITLE
API 정확률

### ISSUE THREAD

**Issue by daeng325** [kookmin-sw/2019-cap1-2019_10#19]
API가 믿을만 한 것인지 테스트를 해 볼 필요가 있다. 
테스트 이미지를 100개쯤 넣어서 얼마만큼의 정확률이 나오는지 볼 예정이다.

내가 분류한 감정이랑 API가 분류한 감정이랑 얼마만큼의 차이가 생기는지 볼 것이다.

**Comment by daeng325** [comment]
어두울 때, 얼굴의 측면사진일 때 잘 되는지 확인.
초점이 안 맞고 흐릿한 사진일 때 잘 되는지 확인.
가까울 때나 멀 때나 잘 되는지 확인.

얼굴의 반이 잘려서 안 나왔을 때는 결과가 나오지 않음.
너무 아래쪽에서 찍었을 때 얼굴 인식이 되지 않음.

**Comment by daeng325** [comment]
마스크나 가면을 쓰고 있을 때는 얼굴 인식이 되지 않는 점을 어떻게 해결할까? 

추울 때나 미세먼지가 많을 때 마스크를 쓰는 경우가 많은데, 
얼굴을 인식하려면 마스크를 입술 아래까지는 내려서 찍어야 한다. 아예 마스크를 코까지 덮은 상태로는 인식이 되지 않는다.

**Comment by daeng325** [comment]
얼굴의 반이 잘려서 나오거나, 마스크를 쓴 상태이면 결과가 나오지 않는 것을 반영하여

어플을 키면 모델이 나와서 "나와 눈을 맞춰줄래?" 라고 코멘트를 남기는 방법이 있을 것 같다.
인위적으로 "카메라를 정면으로 봐주세요" 라고 하는 것보다는 
저런 멘트를 남겨서 사용자가 자연스럽게 얼굴인식되는 범위로 핸드폰을 가져갈 수 있게끔 만드는 것이다.

그렇게 하면 너무 아래쪽에서 찍었을 때 얼굴 인식이 되지 않는 점도 커버할 수 있을 것 같다.

**Comment by daeng325** [comment]
감정인식 면에서

대체적으로 잘 나오긴 하지만, 최종적으로 한 가지 감정만 고려하는 거면 인간이 분류한 감정과 조금씩 어긋나는 것을 볼 수 있었다. 

예를들어, 정말 우리가 보기에 슬퍼하는 표정인데도 불구하고 제일 큰 감정은 중립이 나오는 경우가 있다.

여러가지 사진을 넣으며 확인해 보니, 이것은 슬픔의 표정인데도 불구하고 슬픔이 0%가 나오는 경우는 없었다. 하지만 보편적으로 중립이나 행복이 많이 나오는 것을 볼 수 있었다.

![image](https://user-images.githubusercontent.com/21410809/56073635-7517d900-5de2-11e9-9d02-600cf5644adf.png)

그래서 이런 복합적인 감정을 고려한 방안을 어떻게 마련할 것인지 생각해봐야 할 것 같다.

**Comment by Jeunna** [comment]
https://github.com/justadudewhohacks/face-api.js

**Comment by daeng325** [comment]
live demos 에서 Face Expression Recognition 사용해보려고 했는데 결과가 나오지 않음.. 
나만 안나와? :(

**Comment by Jeunna** [comment]
![2](https://user-images.githubusercontent.com/21366540/56091217-d2954e00-5ee6-11e9-827f-28a22055ded4.PNG)

![1](https://user-images.githubusercontent.com/21366540/56091208-a974bd80-5ee6-11e9-99dd-17b6833a3bb1.PNG)

나는 나오는뎅...?

**Comment by daeng325** [comment]
![image](https://user-images.githubusercontent.com/21410809/56114982-590c6700-5f9d-11e9-8949-a6766347a353.png)

모델이 무겁나봐,,,

**Comment by daeng325** [comment]
시간관계 상 Microsoft Face API를 그대로 사용하기로 결정.  추천 알고리즘에서 중립이나 행복 등만 주로 나왔을 때 어떻게 처리할 것인지 결정 예정.
