### ISSUE TITLE
노래 분류 알고리즘 

### ISSUE THREAD

**Issue by eunchae0280** [kookmin-sw/2019-cap1-2019_10#20]
노래분류를 기계적으로 어떻게 할 것인가? 다양한 알고리즘을 알아보고 구현해보자.

**Comment by wsubin** [comment]
Musicovery는 무드(mood) 정보를 기반으로 음 악을 검색, 추천해주는 시스템을 제공하며, 장르와 시대 정보를 동시에 제공하 는 인터페이스를 지니고 있다. 홈페이지에서 API에서 확인해볼 것.
http://b2b.musicovery.com

**Comment by ddi04078** [comment]
TFIDF 알고리즘으로 키워드 추출해 노래 가사 분석후, 감정 매칭

**Comment by ddi04078** [comment]
설문조사를 통해 사람들이 감정에 따라 듣는 노래 장르를 통계내기

**Comment by eunchae0280** [comment]
노래분류 결과를 감정으로 바로 매치가 가능할까? 조금 불가능 할 것 같음. 다양한 방법으로 노래의 분류가 끝나면 감정으로 매치할 만한 논문 근거를 찾아보는게 좋을 것 같다.

**Comment by eunchae0280** [comment]
이러한 논문적 근거가 있음
https://www.slideshare.net/mobile/smrl7460/paper-review-85056441
![image](https://user-images.githubusercontent.com/48341169/55850455-58379780-5b8f-11e9-81a4-3cf975a2ea9d.png)
https://trigger.tistory.com/m/274 실제로 기분에 따라 노래를 들을수 있는 소프트웨어

**Comment by eunchae0280** [comment]
https://junhewk.github.io/text/2017/11/10/melonchart-lyrics/
k-pop가사분석

**Comment by wsubin** [comment]
https://www.last.fm/api
태그를 통한 무드별 노래 분류

**Comment by wsubin** [comment]
last.fm이나 allmusic을 통핸 소셜 tagging은 외국 노래 위주.
벅스나 멜론의 tagging을 사용하는 것도 괜찮은 것 같음
