### ISSUE TITLE
어플의 경쟁력

### ISSUE THREAD

**Issue by daeng325** [kookmin-sw/2019-cap1-2019_10#21]
시중에 나온 다른 어플들 사이에서의 경쟁력을 논해봐야 한다.

**Comment by ddi04078** [comment]
우리 어플리케이션은 얼굴인식, 음성인식을 통해서 감정에 맞는 노래를 추천하는 어플이다. 

시중에 나온 어플을 분석한 결과 얼굴을 인식해서 연령 성별을 분석 / 감정에 대한 일기를 쓰기 / 단순히 좋은 노래를 추천받는 등의 어플들은 있었지만, 사용자가 지금 어떤 감정인지 그리고 이때 어떤 노래를 추천받을 수 있는지에 대한 어플은 없었다.

우리 어플은, 감성 인식 기술측면에서 현대인들이 자신의 감정을 제대로 알지도못하고 바쁘게 살아가는 사회속에서 본인의 감정을 분석해 바르게 인식하게 해준다.  또한 사람들이 가장 친숙하게 접하는 ‘노래’라는 소재를 활용해서,  분석된 ‘자신’의 감정에 따른 노래 추천이라는 주제이다. 이런 점에서 우리 어플은 충분히 경쟁력이 있다고 본다.

그리고 ‘스노우’라는 어플은 사람들의 얼굴을 인식해 재미있는 스티커를 붙여주는 단순한 기능으로 선풍적인 인기를 누렸다.  우리 프로젝트도 노래 추천하는 도중, 연령을 반영해서 향수를 불러일으킬 노래를 추천한다든지 웃는 얼굴로 슬픈 말을 한다든지의 모순적인 상황에서 거짓말에 대한 노래를 추천한다든지 등
재미있는 요소를 가미하는 것도 또한 어플의 경쟁력을 높일 것이라고 생각한다.
