### ISSUE TITLE
동영상 재생

### ISSUE THREAD

**Issue by Jeunna** [kookmin-sw/2019-cap1-2019_10#25]
- [ ] 유튜브 api를 사용하여 구현
- [ ] 유니티 youtube video player 에셋을 이용하여 구현
- [x] 이미지를 클릭하면 하이퍼링크로

세 개 중 하나의 방법으로 할 예정..

**Comment by Jeunna** [comment]
[C#에서 YouTube API 사용하기](http://www.csharpstudy.com/Practical/Prac-youtube-api.aspx)

**Comment by eunchae0280** [comment]
https://github.com/youtube/api-samples/blob/master/python/search.py

**Comment by Jeunna** [comment]
[unity jar 파일 이클립스 연동](https://hyunity3d.tistory.com/521)
[unity 안드로이드 플러그인 빌드](https://docs.unity3d.com/kr/530/Manual/PluginsForAndroid.html)

**Comment by Jeunna** [comment]
Application.OpenURL("https://www.youtube.com/"); 사용하기로 함
