### ISSUE TITLE
Django와 RDS 인스턴스 연동

### ISSUE THREAD

**Issue by daeng325** [kookmin-sw/2019-cap1-2019_10#26]
생성한 RDS 인스턴스에 로컬에 미리 만들어놓은 데이터베이스를 이주시키는 방법을 알아보자.

**Comment by wsubin** [comment]
참고할것
https://nachwon.github.io/django-deploy-5-rds/
http://blog.naver.com/PostView.nhn?blogId=carrotcarrot&logNo=220671342353
