### ISSUE TITLE
추천 알고리즘에서 Database 접근 문제

### ISSUE THREAD

**Issue by ddi04078** [kookmin-sw/2019-cap1-2019_10#29]

**Comment by ddi04078** [comment]
추천 알고리즘에서 DB에 다시 접근하는 것은 비효율적이다. 
(1) c++로 연산을 최대한 처리한 후, 데이터를 웹서버로 넘겨 웹서버로 나머지 처리를 한다. 웹서버는 연령 정보도 가지고 있으므로 최종적으로 디비에 접근할 수 있고 노래도 선택할 수 있다. 
(2) 추천 알고리즘을 python으로 다시 작성

--> (1) 선택하기로 함. 대신 내 로컬 컴퓨터에 테스트 서버와 테스트 DB를 만들고 테스트 해야함

**Comment by daeng325** [comment]
서버 컴퓨터에서 테스트하였고 django 자체에서 데이터베이스에 접근했음.
