### ISSUE TITLE
어플 -> API 서버 정보 전달 방법

### ISSUE THREAD

**Issue by daeng325** [kookmin-sw/2019-cap1-2019_10#3]
이미지를 받아올 때, 
앱에서 이미지 파일을 저장하여 그 파일을 보낼 것인지 OR 이미지에 대한 matrix로 보낼 것인지 정하기

음성 데이터를 받아올 때,
앱에서 .wav 파일이나 .mp3 파일로 보낼 것인지 OR 음성에 대한 데이터 리스트로 보낼 것인지 정하기

**Comment by Jeunna** [comment]
유니티에서 사진을 받아오는 방식이 GetPixels라서 전체 픽셀의 색상 배열을 반환함
반환된 배열은 2차월 배열이며 해당 픽셀은 왼쪽에서 오른쪽으로, 위에서 아래 방향의 순서로 놓여져있음
[해당 Unity Documentation 주소](https://docs.unity3d.com/kr/530/ScriptReference/WebCamTexture.GetPixels.html)


배열을 .PNG, .JPG, .EXR, .TGA 형식으로 encoding도 가능
지금은 확인하기 편하도록 .PNG로 구현해놓음

**Comment by daeng325** [comment]
카카오톡이나 다른 메신저처럼 갤러리에 있는 사진이 아닌 그때그때 촬영해서 보내는 사진이라면 로컬에 굳이 저장되어 있지 않아도 된다고 생각한다. 그러므로 파일로 저장하여 보내는 것이 아닌 , 반환된 색상 배열을 그대로 서버에 보내는 게 낫지 않나 싶다.

Unity에서 색상 배열을 그대로 보냈을 때 그것에 대한 데이터를 api에 어떤 식으로 전송시켜야 할지 알아보겠음.

**Comment by daeng325** [comment]
API Request Body 를 확인한 결과 

To detect in a URL (or binary data) specified image. 

이렇게 나와있다. 즉 , url을 따로 생성해주지 않아도 됨.
png 파일 그대로도 face detect 함수에 파라미터로 넘겨줄 수 있는 것이었다. 

png 파일을 보내지 않을 거라고 했으니 그 색상 배열을 binary data로 보내줄 수 있는지 확인 바람.

**Comment by Jeunna** [comment]
이게 세가지가 있는데

GetPixel : 좌표 (x, y)의 픽셀 색상을 반환합니다.
GetPixels : 픽셀 색상의 블록을 받아옵니다.
GetPixels32 : Color32 포맷으로 픽셀 색상의 블록을 가져옵니다.
Pixels로 해야할까 Pixels32로 해야할까..?

BinaryFormatter는 '파라미터를 갖지 않는 생성자'를 갖는 클래스라면 어떤 클래스도 바이트 배열로 변환할 수 있습니다.
라고 해서 이걸 사용해서 한 번 해보겠음.

**Comment by daeng325** [comment]
https://docs.gamesparks.com/tutorials/game-engine-integrations/unity-uploading-and-retrieving-images.html
여기에서 UploadFile()함수가 도움이 될 수 있을지는 모르겠지만 올려봄,,
ReadPixels는 파일이 있어야만 읽을 수 있는 건가...?잘 모르겠다

GetPixels랑 Getpixels32는 비교가 많이 되어 있는데, Getpixels32가 좀 더  빠르고 Getpixel을 반복적으로 호출할 수 있다는 것 같았음.
Using GetPixels32 can be faster than calling GetPixel repeatedly, especially for large textures. In addition, GetPixels32 can access individual mipmap levels.

**Comment by Jeunna** [comment]
메모
[HTTP 서버로 양식 보내기(POST): 두가지 방법이 있다](https://docs.unity3d.com/kr/2017.4/Manual/UnityWebRequest-SendingForm.html)

일단 해보고 다시 돌아올게..

**Comment by Jeunna** [comment]
CSRF......CROSS-SITE REQUEST FORGERY 관련 자료들

[CSRF가 무엇인가에 대한 설명과 전반적인 django에 대한 설명과 기타등등 아름다운 자료 ](https://www.slideshare.net/EunhyangKim2/ss-118560530)


+ [Django csrf token + Angularjs](https://stackoverflow.com/questions/18156452/django-csrf-token-angularjs)
+ [UnityWebRequest returns HTTP Status 408 while calling Bing Speech API](https://stackoverflow.com/questions/49655980/unitywebrequest-returns-http-status-408-while-calling-bing-speech-api)
+ [How do i transfer images from Unity to Django server?](https://stackoverflow.com/questions/18156452/django-csrf-token-angularjs)
+ [장고Django-개발-폼Form-관리와-CSRF-취약점-해결](https://heiswed.tistory.com/entry/%EC%9E%A5%EA%B3%A0Django-%EA%B0%9C%EB%B0%9C-%ED%8F%BCForm-%EA%B4%80%EB%A6%AC%EC%99%80-CSRF-%EC%B7%A8%EC%95%BD%EC%A0%90-%ED%95%B4%EA%B2%B0)
+ [장고 폼](https://tutorial.djangogirls.org/ko/django_forms/)
+ [https://docs.djangoproject.com/ko/2.2/intro/tutorial04/](https://docs.djangoproject.com/ko/2.2/intro/tutorial04/)
+ [CSRF TOKEN in DJANGO](http://www.iorchard.net/2016/07/11/curl_django_csrf_token_transmit.html)
+ [Unity docs](https://docs.unity3d.com/kr/2017.4/Manual/UnityWebRequest-SendingForm.html#UsingWWWForm)
+ [Unity Web Request + Django: CSRF token missing or incorrect
](https://stackoverflow.com/questions/50313537/unity-web-request-django-csrf-token-missing-or-incorrect)

**Comment by daeng325** [comment]
https://stackoverflow.com/questions/16599979/django-rest-framework-csrf-failed-csrf-cookie-not-set

이렇게 하는 방법도 있다는데... 혹시 간단하게 pull 받은 거에서 실행시켜 볼 수 있나?

**Comment by daeng325** [comment]
임시방편으로 이 방법을 생각했는데, 단순히 한 라인을 삭제하면 될 것 같다.  한 번 해보길 바람.

![image](https://user-images.githubusercontent.com/21410809/56078860-a8c92200-5e27-11e9-923c-0c7bf8388dab.png)

안 되면 알려줘 :(

**Comment by daeng325** [comment]
https://stackoverflow.com/questions/50313537/unity-web-request-django-csrf-token-missing-or-incorrect

    // get the csrf cookie
    string SetCookie = loginPage.GetResponseHeader ("set-cookie");
    Debug.Log (SetCookie);
    Regex rxCookie = new Regex("csrftoken=(?<csrf_token>.{64});");
    MatchCollection cookieMatches = rxCookie.Matches (SetCookie);
    string csrfCookie = cookieMatches[0].Groups ["csrf_token"].Value;

    // get the middleware value
    string loginPageHtml = loginPage.downloadHandler.text;
    Regex rxMiddleware = new Regex("name='csrfmiddlewaretoken' value='(?<csrf_token>.{64})'");
    MatchCollection middlewareMatches = rxMiddleware.Matches(loginPageHtml);
    string csrfMiddlewareToken = middlewareMatches[0].Groups ["csrf_token"].Value;

위와 같이 유니티 자체에서 get csrf token 을 하던데 이것도 해 봤는지..?

**Comment by daeng325** [comment]
https://stackoverflow.com/questions/49654791/how-to-send-images-from-unity-to-django-through-json-type

이미지를 json 형태로 유니티에서 django로 보내는 방법

**Comment by Jeunna** [comment]
[Unity 2017.3 HTTP POST request always empty (Django web app)](https://forum.unity.com/threads/unity-2017-3-http-post-request-always-empty-django-web-app.517123/)

**Comment by daeng325** [comment]
formdata POST 받는 방법 해결. (chunkedTransfer = false) 

이제 csrf token issue만 해결하면 될 것 같다.

**Comment by daeng325** [comment]
* Unity code

![image](https://user-images.githubusercontent.com/21410809/58148487-ef693200-7c99-11e9-80c9-e14579ad430e.png)


*Django code

![image](https://user-images.githubusercontent.com/21410809/58148515-10ca1e00-7c9a-11e9-9aa8-a86827a40d03.png)
