### ISSUE TITLE
c++(추천알고리즘)과 python(서버) 연동

### ISSUE THREAD

**Issue by ddi04078** [kookmin-sw/2019-cap1-2019_10#30]
1.
프로세스 2개 띄워두고 파이프로 연결하는 방법이 있다. 서버와 알고리즘의 프로그램 2개를 따로 돌리는 것이다. 요청 받을때까지 기댜렸다가, 요청 오면 데이터를 전달하면 된다. python 라이브러리의 os 또는 server process 에 해당한다. 
-> 추천 알고리즘이 독립적인 응용프로그램이 아니기 때문에 프로세스를 2개 띄우는 방법은 지양한다. 

2.
추천 알고리즘을 함수로 만들어놓고, dll로 export해서 파이썬에서 호출해 사용하는 방법이 있다. (동적링크라이브러리) 컴파일할때 dll 따로해야한다.

**Comment by daeng325** [comment]
DLL을 쓰지 않고 파이썬으로 작업했으므로 이슈 닫겠음.
