### ISSUE TITLE
이미지 분석 검토

### ISSUE THREAD

**Issue by Jeunna** [kookmin-sw/2019-cap1-2019_10#34]
ms face api를 사용해 구현을 했는데 connection 오류가 잦아서 어떻게 해결할지 생각해보자꾸

+ https://github.com/justadudewhohacks/face-api.js

**Comment by daeng325** [comment]
위의 api는 자바스크립트라서 node js 적용방법 밖에 없어서 
python 패키지 중 nodeenv npm 을 다운받은 후에 
자바스크립트 코드를 파이썬으로 바꿔주는 js2py 를 적용했는데 
face-api.js 해당하는 패키지가 import가 되지 않음. :(

python 환경으로 하려면 이상한 거 다 다운받아야 되고 다운받아도 안됨 
node js 서버로 갈아치우는게 빠를거같은데 그럴시간이 있을까..

**Comment by Jeunna** [comment]
- https://github.com/omar178/Emotion-recognition
- https://github.com/petercunha/Emotion
- https://github.com/JostineHo/mememoji
- https://github.com/oarriaga/face_classification

😱🤮😭

**Comment by daeng325** [comment]
위의 https://github.com/omar178/Emotion-recognition 로 api 결정 후 적용 완료. 
하지만 이 api에는 사용자의 나이정보를 얻어오지 못하므로 본 프로젝트에서 age는 0세~150세 랜덤으로 돌리는 방법으로 결정.
