### ISSUE TITLE
음성데이터전송&결과값문제

### ISSUE THREAD

**Issue by eunchae0280** [kookmin-sw/2019-cap1-2019_10#6]
어플리케이션에서 입력받은 음성데이터를 어떤형태로 서버에 전송할 것 인가??
wav형태로 할 경우 txt나 jpg보다 용량이 크기때문에 발생하는 문제..

음성데이터로 판단하는 감정 결과값은 각 감정에대한 %인지, 얼굴인식 결과에 보탬이 될 수 있는 1개의 감정값만 필요한지??

**Comment by ddi04078** [comment]
최종결과가 각 감정에 대한 비율인 채로 추천 알고리즘의 입력으로 들어갈 것 같다. 
음성데이터의 결과가 각 감정에 대한 비율이면 제일 통일성 있고,
3위까지만 추출해도 괜찮은 방법인 것 같고,
1개의 감정값을 사용하려면 최종결과를 내는 방안을 생각해봐야할 것 같다.
