### ISSUE TITLE
음성-감정 모델의 기술적 현실성 검토와 논의

### ISSUE THREAD

**Issue by ddi04078** [kookmin-sw/2019-cap1-2019_10#8]
#8 음성-감성 모델에서, 톤과 억양으로 감정을 detection하는 문제에서 현실적인 어려움이 있다. 일을 줄여서 가능한 영역에서 진행하려고 한다. 음성API를 활용해 텍스트분석을 할 것인지 등의 검토와 논의가 필요하다.

**Comment by daeng325** [comment]
톤과 억양으로 감정을 분석하는 모델을 만들 경우 정확도를 올리는 데에 한계가 있을 것이고, 정해진 시간 안에 완성해야된다는 시간적 제한도 있어서 모델을 만들어 학습시키는 과정은 생략하기로 하였다.

**Comment by daeng325** [comment]
대신, 많은 STT api를 사용하여 텍스트로 변환 후, 그 텍스트를 이용해 감정을 분석하는 방향으로 가자고 결정하였다. 그에 대한 방법은 따로 더 논의해보기로 한다.

**Comment by eunchae0280** [comment]
방법1. Google Cloud Natural Language API, Google Cloud Speech-To-Text API를 같이 사용하여 음성을 통한 감정분석을 한다.

**Comment by eunchae0280** [comment]
방법을 더 찾아본 결과, 음성을 통한 감정분석 모델에서 오픈소스API를 사용하는데에 3가지가 사용이 된다. 1.  Google Cloud Speech-To-Text API, 2.Google Cloud Natural Language API, 세번째는 1번의 API가 한국어 지원이 아직 되지 않기때문에 중간단계로 간단한 영어로 번역할 수 있는 Cloud Translation이 사용된다.
이렇게 3가지를 활용하여 음성을 통한 감정 분석을 하는 것이 과연 효과적인가?
