### ISSUE TITLE
노래 추천알고리즘 설계 중 많은 경우의 수 문제

### ISSUE THREAD

**Issue by ddi04078** [kookmin-sw/2019-cap1-2019_10#9]
#9 많은 사용자 환경에서 노래 추천 알고리즘의 성능을 끌어올릴 수 있을 다양한 데이터와 예측, 확률 계산 등이 필요하다.

**Comment by ddi04078** [comment]
1. **감정 : 음악**을 매칭해두고, 추천알고리즘에서 이를 상황에 따라 적용한다. 최종감정 결과에서 **여러 감정이 여러 비율로 나타나기** 때문에, 한 추천에 서로 다른 '감정 : 음악'을 사용할 수도 있고 3순위까지 추천을 할 수 있게 한다.

**Comment by ddi04078** [comment]
2. 감정에 따른 음악 종류를 소분류해서 나타낸다. 예를 들어 1순위 감정이 '슬픔'일 때, 슬픔에 대한 추천 음악 종류는 잔잔한 노래 / 너무 슬퍼서 울고싶은 노래 / 기분을 전환할 밝은 노래로 소분류할 수 있다. 그러면 더 다양한 경우에 대비할 수 있을 것이다.

**Comment by ddi04078** [comment]
3. 감정비율 뿐만 아니라 사용자의 연령도 고려해야한다.

**Comment by daeng325** [comment]
감정결과는 8개가 각각의 비율로 나올 것이다. 예를들어, anger : 0.008% , contempt : 0.0001%.....일 것이다. 
노래를  추천할 때에는 비율이 높게 나온 감정 3순위까지를 다 고려해서 추천할 수 있게 할 예정이다. 
분석이 끝나면 사용자에게 노래 3개를 추천해주면서 왜 이런 노래를 추천했는지에 대한 설명으로 감정해시태그를 제공할 예정이다. 

ex)
#anger #happiness #sadness
